trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildConfiguration: 'Release'
  artifactName: 'WebApp'
  webProject: 'ST10398576_Disaster Alleviation Foundation\\ST10398576_Disaster Alleviation Foundation.csproj'
  azureSubscription: 'azureServiceConnection'
  webAppName: 'ST10398576-DisasterAlleviationFoundation'

steps:
- task: UseDotNet@2
  displayName: 'Install .NET SDK'
  inputs:
    packageType: 'sdk'
    version: '8.x'
    installationPath: $(Agent.ToolsDirectory)/dotnet

- task: DotNetCoreCLI@2
  displayName: 'Restore NuGet packages'
  inputs:
    command: 'restore'
    projects: '$(Build.SourcesDirectory)/**/*.csproj'

- task: DotNetCoreCLI@2
  displayName: 'Build solution'
  inputs:
    command: 'build'
    projects: '$(solution)'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'Run tests (exclude UI)'
  inputs:
    command: 'test'
    projects: '$(solution)'
    arguments: '--configuration $(buildConfiguration) --no-build --filter "TestCategory!=UI"'

- task: DotNetCoreCLI@2
  displayName: 'Publish web project'
  inputs:
    command: 'publish'
    projects: '$(webProject)'
    arguments: '--configuration $(buildConfiguration) --output "$(Build.ArtifactStagingDirectory)\\publish"'

- task: ArchiveFiles@2
  displayName: 'Create zip from published output'
  inputs:
    rootFolderOrFile: '$(Build.ArtifactStagingDirectory)\\publish'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)\\WebApp.zip'
    replaceExistingArchive: true

- task: PublishBuildArtifacts@1
  displayName: 'Publish artifact: WebApp.zip'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: '$(artifactName)'
    publishLocation: 'Container'

- task: AzureWebApp@1
  displayName: 'Deploy Web App to Azure'
  inputs:
    azureSubscription: '$(azureSubscription)'
    appType: 'webApp'
    appName: '$(webAppName)'
    package: '$(Build.ArtifactStagingDirectory)\\WebApp.zip'
  condition: succeeded()